/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardSettrings: typeof import('./src/components/CardSettrings.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBtn: typeof import("element-plus/es")["ElBtn"]
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCardTitle: typeof import("element-plus/es")["ElCardTitle"]
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptions: typeof import("element-plus/es")["ElOptions"]
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Locale: typeof import('./src/components/locale/index.vue')['default']
    LocaleBlock: typeof import('./src/components/locale/LocaleBlock.vue')['default']
    LocaleSwitcher: typeof import('./src/components/locale/LocaleSwitcher.vue')['default']
    MenuAside: typeof import('./src/components/MenuAside.vue')['default']
    MultiEditor: typeof import('./src/components/photoEditor/MultiEditor.vue')['default']
    PhohoInfo: typeof import("./src/components/PhohoInfo.vue")["default"]
    PhotoCard: typeof import('./src/components/PhotoCard.vue')['default']
    PhotoFilter: typeof import('./src/components/PhotoFilter.vue')['default']
    PhotoParamsEditor: typeof import('./src/components/photoEditor/PhotoParamsEditor.vue')['default']
    PhotoParamsHeader: typeof import('./src/components/photoEditor/PhotoParamsHeader.vue')['default']
    PhotoPreviewCollapse: typeof import('./src/components/photoEditor/PhotoPreviewCollapse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploaderCard: typeof import('./src/components/photoEditor/UploaderCard.vue')['default']
    UploaderWatermarkCard: typeof import('./src/components/watermark/UploaderWatermarkCard.vue')['default']
    WatermarkCard: typeof import('./src/components/watermark/WatermarkCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
